files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  final-newline: 0
  indentation: 0
  leading-zero: 0
  no-css-comments: 0
  property-sort-order: 0
  quotes:
    - 1
    - style: double
