language: node_js
sudo: false
node_js:
  - '4.2.4'
before_script:
  - npm install -g grunt
script:
  - grunt dev
  - grunt dist
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
