language: node_js
sudo: false
node_js:
  - '4.0.0'
  - '4.8.4'
  - '5.12.0'
  - '6.11.1'
  - '7.10.1'
  - '8.1.4'
before_script:
  - npm install -g grunt
script:
  - grunt dev
  - grunt dist
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
